name: LocalLoop
options:
  bundleIdPrefix: com.example  # Change to your bundle ID prefix
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES

packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "7.0.0"
  GoogleAPIClientForREST:
    url: https://github.com/google/google-api-objectivec-client-for-rest
    from: "3.0.0"

targets:
  LocalLoop:
    type: application
    platform: iOS
    sources:
      - path: LocalLoop
        excludes:
          - "**/*.plist"
    dependencies:
      - package: GoogleSignIn
      - package: GoogleAPIClientForREST
        product: GoogleAPIClientForREST_Drive
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.localloop  # Change to your bundle ID
        INFOPLIST_FILE: LocalLoop/Resources/Info.plist
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Local Loop records audio to create searchable transcripts of your day."
        INFOPLIST_KEY_UIBackgroundModes: "audio fetch processing"
        CODE_SIGN_STYLE: Automatic
    info:
      path: LocalLoop/Resources/Info.plist
      properties:
        UIBackgroundModes:
          - audio
          - fetch
          - processing
        NSMicrophoneUsageDescription: "Local Loop records audio to create searchable transcripts of your day."
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - com.googleusercontent.apps.YOUR_GOOGLE_CLIENT_ID

  LocalLoopTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - LocalLoopTests
    dependencies:
      - target: LocalLoop
